### ISSUE TITLE
Hay que ajustar tamaño fuentes HTML de acuerdo al grado

### ISSUE THREAD

**Issue by enriqueacosta** [enriqueacosta/IllustrativeMath-GrupoLEMA#84]

**Comment by enriqueacosta** [comment]
Lista la estrategia. Consiste de:

*  un css específico para estudiantes `custom-styles-est.css` que carga el archivo por defecto `custom-styles-est.css`
*  un css específico para cada grado, que carga `custom-styles-est.css`. Para grado 3, se llama `grado3-est.css`

Todos estos css están en la carpeta de `/assets/css`.

El css se carga desde el archivo `project.ptx`.
```xml
<target name="gra3-uni4-web-est" 
      format="html" 
      source="gra3-uni4/gra3-uni4.ptx"
      publication="publication-est-web.ptx"
      output-dir="web-est/gra3-uni4">
      <stringparams author.tools="yes" html.css.extra="external/css/grado3-est.css"/>
</target>
```

**Comment by enriqueacosta** [comment]
De pronto es buena idea implementar una estrategia para agrandar todas las imágenes por un factor de escala (porque muchas no tienen la escala correcta para el texto grande), pero no he logrado hacer que funcione bien algo por el estilo:
```css
img {
    transform: scale(1.3);
    max-width: 100%
}
```
Lo que no funciona es que el max-width no queda en 100% sino en 130%, entonces las imágenes grandes se salen de su espacio.

Un alternativa es:
```css
img {
    max-width: calc(100% / 1.3); /* Adjust width according to scale */
    height: auto;
    transform: scale(1.3);
}
```
pero tampoco funciona del todo porque no se agranda el espacio vertical para la imagen agrandada.
