### ISSUE TITLE
los PP deberían decir `Problema XX` en la numeración

### ISSUE THREAD

**Issue by enriqueacosta** [enriqueacosta/IllustrativeMath-GrupoLEMA#88]
<img width="500" alt="Screenshot 2024-10-22 at 11 29 26 PM" src="https://github.com/user-attachments/assets/5dd83e5d-6c63-4e40-84cb-fcb0280994e5">

En HTML, es agregar algo por el estilo de:
```css
.codenumber::before {
    content: "Problema ";
}
```
Pero se debe ajustar el alcance, para que solo aplique a los PPs (que son `<exercise>`).
